using System;
using InvalidDataError = Milese.Common.Shared.InvalidData;

namespace Milese.Common.Shared;

/// <summary>
/// Contract for domain value types whose underlying value is a
/// <see cref="DateTime"/> (<see cref="IValueType{TSelf, T}"/> with
/// <c>T = DateTime</c>). Specialises the value type by adding the field name
/// (<see cref="FieldName"/>) used when generating validation errors and the
/// <c>Parse</c> factories for trusted (already valid) and untrusted (string /
/// <see cref="DateTime"/>) input.
/// </summary>
/// <remarks>
/// The valid range accepted by <c>Parse</c> is a year strictly greater than 2020
/// and strictly lower than 2099 by default — a sanity guard against clearly-bogus
/// dates, not a business rule; a concrete type may override <see cref="MinYear"/>/
/// <see cref="MaxYear"/> if a tighter range applies. As with the other value-type
/// contracts, the <c>static abstract</c> members are implemented in each concrete
/// type because C# interface <c>static</c> members can only be reached through a
/// generic type parameter, whereas call sites use the concrete type directly.
/// </remarks>
/// <typeparam name="TSelf">The value type that implements this interface.</typeparam>
public interface IDateTimeValueType<TSelf> : IValueType<TSelf, DateTime>
    where TSelf : IDateTimeValueType<TSelf>, new()
{
    /// <summary>
    /// Minimum accepted year (exclusive). Only dates with
    /// <c>Year &gt; MinYear</c> are valid.
    /// </summary>
    static int MinYear => 2020;

    /// <summary>
    /// Maximum accepted year (exclusive). Only dates with
    /// <c>Year &lt; MaxYear</c> are valid.
    /// </summary>
    static int MaxYear => 2099;

    /// <summary>
    /// Field name used when constructing validation errors
    /// (<see cref="InvalidDataError"/>) generated by <see cref="ValueTypeParser"/>.
    /// </summary>
    static abstract string FieldName { get; }

    /// <summary>
    /// Validates and constructs the value type from a <see cref="DateTime"/>.
    /// The typical implementation delegates to
    /// <see cref="ValueTypeParser.DateTimeInRange{TSelf}(DateTime, string)"/>.
    /// </summary>
    static abstract Result<TSelf, InvalidDataError> Parse(DateTime value);

    /// <summary>
    /// Validates and constructs the value type from its string representation.
    /// The typical implementation delegates to
    /// <see cref="ValueTypeParser.DateTimeInRange{TSelf}(string, string)"/>.
    /// </summary>
    static abstract Result<TSelf, InvalidDataError> Parse(string? value);
}
