using System;
using System.Threading.Tasks;
using InvalidDataError = Milese.Common.Shared.InvalidData;

namespace Milese.Common.Shared;

/// <summary>
/// Contract for domain value types that represent an identifier
/// (<see cref="IValueType{TSelf, T}"/> with <c>T = int</c>). Specialises the value
/// type by adding the field name (<see cref="FieldName"/>) used when generating
/// validation errors, so each identifier only needs to declare that name and delegate
/// the remaining logic to <see cref="ValueTypeParser"/>.
/// </summary>
/// <remarks>
/// The interface requires each identifier to declare <c>Parse</c>/<c>ParseAsync</c>
/// via <c>static abstract</c> members. They are implemented in each concrete type
/// (rather than with a default implementation) because in C# interface <c>static</c>
/// members can only be called through a generic type parameter, whereas call sites
/// call the concrete type directly (e.g. <c>LessonId.Parse(...)</c>).
/// </remarks>
/// <typeparam name="TSelf">The value type that implements this interface.</typeparam>
public interface IIdValueType<TSelf> : IValueType<TSelf, int>
    where TSelf : IIdValueType<TSelf>, new()
{
    /// <summary>
    /// Field name used when constructing validation errors
    /// (<see cref="InvalidDataError"/>) generated by <see cref="ValueTypeParser"/>.
    /// </summary>
    static abstract string FieldName { get; }

    /// <summary>
    /// Validates and constructs the identifier from its underlying value.
    /// The typical implementation delegates to
    /// <see cref="ValueTypeParser.StrictlyPositive{TSelf}(int, string)"/> using
    /// <see cref="FieldName"/>.
    /// </summary>
    static abstract Result<TSelf, InvalidDataError> Parse(int value);

    /// <summary>
    /// Validates the identifier and asynchronously checks that it exists.
    /// The typical implementation delegates to
    /// <see cref="ValueTypeParser.ParseIdAsync{TSelf}(int, string, Func{TSelf, Task{bool}})"/>
    /// using <see cref="FieldName"/>.
    /// </summary>
    static abstract Task<Result<TSelf, InvalidDataError>> ParseAsync(int value, Func<TSelf, Task<bool>> exists);
}
