//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milese.Common.Shared.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Milese.Common.Shared.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string for the MinLength constraint. {0}=FieldName, {1}=min length.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the MaxLength constraint. {0}=FieldName, {1}=max length.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the MinValue constraint. {0}=FieldName, {1}=min value.
        /// </summary>
        public static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the MaxValue constraint. {0}=FieldName, {1}=max value.
        /// </summary>
        public static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the EnumNotDefined constraint. {0}=FieldName.
        /// </summary>
        public static string EnumNotDefined {
            get {
                return ResourceManager.GetString("EnumNotDefined", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the IdNotFound constraint. {0}=FieldName.
        /// </summary>
        public static string IdNotFound {
            get {
                return ResourceManager.GetString("IdNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the FormatInvalid constraint. {0}=FieldName.
        /// </summary>
        public static string FormatInvalid {
            get {
                return ResourceManager.GetString("FormatInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the CanNotBeNull constraint. {0}=FieldName.
        /// </summary>
        public static string CanNotBeNull {
            get {
                return ResourceManager.GetString("CanNotBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the CanNotBeEmptyOrNull constraint. {0}=FieldName.
        /// </summary>
        public static string CanNotBeEmptyOrNull {
            get {
                return ResourceManager.GetString("CanNotBeEmptyOrNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the StrictlyPositive constraint. {0}=FieldName.
        /// </summary>
        public static string StrictlyPositive {
            get {
                return ResourceManager.GetString("StrictlyPositive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the GenericError constraint. {0}=FieldName.
        /// </summary>
        public static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the AlreadyExists constraint. {0}=FieldName.
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the AlreadyResolved constraint. {0}=FieldName.
        /// </summary>
        public static string AlreadyResolved {
            get {
                return ResourceManager.GetString("AlreadyResolved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the AlreadyAssigned constraint. {0}=FieldName.
        /// </summary>
        public static string AlreadyAssigned {
            get {
                return ResourceManager.GetString("AlreadyAssigned", resourceCulture);
            }
        }
    }
}
