<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Milese.Tests.Integration</RootNamespace>
    <AssemblyName>Milese.Tests.Integration</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="TUnit.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Data\Data.Db\Data.Db.csproj" />
  </ItemGroup>
</Project>
