<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Milese.Services.Core.Tests</RootNamespace>
    <AssemblyName>Milese.Services.Core.Tests</AssemblyName>

    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Services\Services.Core\Services.Core.csproj" />
    <ProjectReference Include="..\Tests.Integration\Tests.Integration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
